OswisOrg\OswisCalendarBundle\Entity\Accommodation\AccommodationFeature:
  attributes:
    id:
      groups: [ 'calendar_accommodation_features_get', 'calendar_accommodation_feature_get', 'calendar_accommodation_unit_get', 'calendar_accommodation_units_get' ]
    name:
      groups: [ 'calendar_accommodation_features_get', 'calendar_accommodation_feature_get', 'calendar_accommodation_features_post', 'calendar_accommodation_feature_put', 'calendar_accommodation_unit_get', 'calendar_accommodation_units_get' ]
    slug:
      groups: [ 'calendar_accommodation_features_get', 'calendar_accommodation_feature_get' ]
    code:
      groups: [ 'calendar_accommodation_features_get', 'calendar_accommodation_feature_get', 'calendar_accommodation_features_post', 'calendar_accommodation_feature_put', 'calendar_accommodation_unit_get', 'calendar_accommodation_units_get' ]
