controllers:
    resource: ../../Controller/
    type: annotation

zakjakub_oswis_calendar_event_participant_web_registration_confirm:
    controller: zakjakub_oswis_calendar.event_participant_web_controller::eventParticipantRegistrationConfirmAction
    path: "/potvrzeni-prihlasky/{token}/{eventParticipantId}"

zakjakub_oswis_calendar_web_event:
    controller: zakjakub_oswis_calendar.event_web_controller::showEvent
    path: "/akce/{slug}"

zakjakub_oswis_calendar_event_web_leaflet:
    controller: zakjakub_oswis_calendar.event_web_controller::eventLeafletPdf
    path: "/letak/{slug}"

zakjakub_oswis_calendar_web_event_participant_registration:
    controller: zakjakub_oswis_calendar.event_participant_web_controller::eventParticipantRegistration
    path: "/akce/{slug}/prihlaska"

zakjakub_oswis_calendar_web_events:
    controller: zakjakub_oswis_calendar.event_web_controller::eventsAction
    path: "/kalendar/{range?}/{start?}/{end?}/{limit?}/{offset?}"
    defaults:
        range: null
        start: null
        end: null
        limit: null
        offset: null

