oswis_org_oswis_calendar_web_event_participant_registration_confirm:
    controller: oswis_org_oswis_calendar.event_participant_controller::eventParticipantRegistrationConfirmAction
    path: "/potvrzeni-prihlasky/{token}/{eventParticipantId}"

oswis_org_oswis_calendar_web_event:
    controller: oswis_org_oswis_calendar.event_controller::showEvent
    path: "/akce/{eventSlug?}"

oswis_org_oswis_calendar_web_event_leaflet:
    controller: oswis_org_oswis_calendar.event_controller::showEventLeaflet
    path: "/letak/{eventSlug?}"

oswis_org_oswis_calendar_web_event_participant_registration:
    controller: oswis_org_oswis_calendar.event_participant_controller::eventParticipantRegistration
    path: "/akce/prihlaska/{eventSlug?}"

oswis_org_oswis_calendar_web_events: ## ??????????????????????????????????????
    controller: oswis_org_oswis_calendar.event_controller::showEvents
    path: "/kalendar/{range?}/{start?}/{end?}/{limit?}/{offset?}"
    defaults:
        range: null
        start: null
        end: null
        limit: null
        offset: null

oswis_org_oswis_calendar_web_events_calendar:
    controller: oswis_org_oswis_calendar.event_controller::showEvents
    path: "/kalendar/{range?}/{rangeValue?}"
    defaults:
        range: null
        rangeValue: null

oswis_org_oswis_calendar_web_events_future:
    controller: oswis_org_oswis_calendar.event_controller::showFutureEvents
    path: "/budouci-akce/{page?}"
    defaults:
        page: null

oswis_org_oswis_calendar_web_events_past:
    controller: oswis_org_oswis_calendar.event_controller::showPastEvents
    path: "/minule-akce/{page?}"
    defaults:
        page: null

