### Endpoint for token processing.
oswis_org_oswis_calendar_participant_process_token:
    controller: oswis_org_oswis_calendar.participant_controller::processToken
    path: "/akce/prihlaska/token/{token}/{participantId}"
    requirements:
        participantId: '\d+'

### Endpoint for (repeated) participant activation request.
oswis_org_oswis_calendar_participant_activation_request:
    controller: oswis_org_oswis_calendar.participant_controller::activationRequest
    path: "/akce/prihlaska/overeni"

oswis_org_oswis_calendar_web_registration:
    controller: oswis_org_oswis_calendar.participant_controller::registration
    path: "/akce/prihlaska/{rangeSlug?}"

oswis_org_oswis_calendar_web_registration_ranges:
    controller: oswis_org_oswis_calendar.participant_controller::showRanges
    path: "/akce/prihlasky/{eventSlug?}/{participantType?}"

oswis_org_oswis_calendar_web_event_leaflet:
    controller: oswis_org_oswis_calendar.event_controller::showEventLeaflet
    path: "/akce/letak/{eventSlug?}"

oswis_org_oswis_calendar_web_events_kalendar: ## ??????????????????????????????????????
    controller: oswis_org_oswis_calendar.event_controller::showEvents
    path: "/akce/kalendar/{range?}/{start?}/{end?}/{limit?}/{offset?}"
    defaults:
        range: null
        start: null
        end: null
        limit: null
        offset: null

oswis_org_oswis_calendar_web_events_calendar:
    controller: oswis_org_oswis_calendar.event_controller::showEvents
    path: "/akce/kalendar/{range?}/{rangeValue?}"
    defaults:
        range: null
        rangeValue: null

oswis_org_oswis_calendar_web_events:
    controller: oswis_org_oswis_calendar.event_controller::showFutureEvents
    path: "/akce/vsechny/{page?}"
    defaults:
        page: null

oswis_org_oswis_calendar_web_events_future:
    controller: oswis_org_oswis_calendar.event_controller::showFutureEvents
    path: "/akce/budouci/{page?}"
    defaults:
        page: null

oswis_org_oswis_calendar_web_events_past:
    controller: oswis_org_oswis_calendar.event_controller::showPastEvents
    path: "/akce/minule/{page?}"
    defaults:
        page: null

oswis_org_oswis_calendar_web_event:
    controller: oswis_org_oswis_calendar.event_controller::showEvent
    path: "/akce/{eventSlug?}"
