##
## OswisCalendarBundle - Services configuration
## oswis-org/oswis-calendar-bundle/Resources/config/services.yaml
##
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    ###
    ### CONTROLLERS
    ###

    ## Controllers wildcard (TODO: To be refactored. Do not use wildcards.)
    OswisOrg\OswisCalendarBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
        public: true

    ## Event controller.
    oswis_org_oswis_calendar.event_controller:
        class: OswisOrg\OswisCalendarBundle\Controller\EventController
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.event_service'
            - '@oswis_org_oswis_calendar.participant_service'
            - '@oswis_org_oswis_calendar.reg_range_service'
    OswisOrg\OswisCalendarBundle\Controller\EventController:
        alias: oswis_org_oswis_calendar.event_controller
        public: true

    ## Participant controller
    oswis_org_oswis_calendar.participant_controller:
        class: OswisOrg\OswisCalendarBundle\Controller\ParticipantController
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.event_service'
            - '@oswis_org_oswis_calendar.reg_range_service'
            - '@oswis_org_oswis_calendar.participant_service'
    OswisOrg\OswisCalendarBundle\Controller\ParticipantController:
        alias: oswis_org_oswis_calendar.participant_controller
        public: true


    ###
    ### SERVICES
    ###

    ### EventFlag Service
    oswis_org_oswis_calendar.event_flag_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventFlagService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\EventFlagService:
        alias: oswis_org_oswis_calendar.event_flag_service
        public: true

    ### EventGroup Service
    oswis_org_oswis_calendar.event_series_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventSeriesService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\EventSeriesService:
        alias: oswis_org_oswis_calendar.event_series_service
        public: true

    ### Event Service
    oswis_org_oswis_calendar.event_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
            - '@oswis_org_oswis_calendar.oswis_calendar_settings_provider'
    OswisOrg\OswisCalendarBundle\Service\EventService:
        alias: oswis_org_oswis_calendar.event_service
        public: true

    oswis_org_oswis_calendar.event_category_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventCategoryService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\EventCategoryService:
        alias: oswis_org_oswis_calendar.event_category_service
        public: true

    oswis_org_oswis_calendar.flag_range_service:
        class: OswisOrg\OswisCalendarBundle\Service\FlagRangeService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\FlagRangeService:
        alias: oswis_org_oswis_calendar.flag_range_service
        public: true

    oswis_org_oswis_calendar.flag_service:
        class: OswisOrg\OswisCalendarBundle\Service\FlagService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\FlagService:
        alias: oswis_org_oswis_calendar.flag_service
        public: true

    oswis_org_oswis_calendar.flag_category_service:
        class: OswisOrg\OswisCalendarBundle\Service\FlagCategoryService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\FlagCategoryService:
        alias: oswis_org_oswis_calendar.flag_category_service
        public: true

    oswis_org_oswis_calendar.participant_payment_service:
        class: OswisOrg\OswisCalendarBundle\Service\ParticipantPaymentService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@mailer.mailer'
            - '@monolog.logger'
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
            - '@oswis_org_oswis_calendar.participant_service'
            - '@oswis_org_oswis_calendar.participant_mail_service'
    OswisOrg\OswisCalendarBundle\Service\ParticipantPaymentService:
        alias: oswis_org_oswis_calendar.participant_payment_service
        public: true

    oswis_org_oswis_calendar.participant_payments_import_service:
        class: OswisOrg\OswisCalendarBundle\Service\ParticipantPaymentsImportService
        autowire: true
        public: true
        arguments:
            - '@monolog.logger'
            - '@oswis_org_oswis_calendar.participant_service'
            - '@oswis_org_oswis_calendar.participant_payment_service'
    OswisOrg\OswisCalendarBundle\Service\ParticipantPaymentsImportService:
        alias: oswis_org_oswis_calendar.participant_payments_import_service
        public: true

    oswis_org_oswis_calendar.participant_service:
        class: OswisOrg\OswisCalendarBundle\Service\ParticipantService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@OswisOrg\OswisCalendarBundle\Repository\ParticipantRepository'
            - '@monolog.logger'
            - '@oswis_org_oswis_core.app_user_service'
            - '@oswis_org_oswis_calendar.participant_token_service'
            - '@oswis_org_oswis_calendar.participant_mail_service'
            - '@oswis_org_oswis_address_book.abstract_contact_service'
            - '@oswis_org_oswis_calendar.flag_range_service'
    OswisOrg\OswisCalendarBundle\Service\ParticipantService:
        alias: oswis_org_oswis_calendar.participant_service
        public: true

    oswis_org_oswis_calendar.participant_token_service:
        class: OswisOrg\OswisCalendarBundle\Service\ParticipantTokenService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
            - '@OswisOrg\OswisCalendarBundle\Repository\ParticipantTokenRepository'
    OswisOrg\OswisCalendarBundle\Service\ParticipantTokenService:
        alias: oswis_org_oswis_calendar.participant_token_service
        public: true

    oswis_org_oswis_calendar.participant_mail_service:
        class: OswisOrg\OswisCalendarBundle\Service\ParticipantMailService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oswis_org_oswis_core.mail_service'
            - '@OswisOrg\OswisCalendarBundle\Repository\ParticipantMailGroupRepository'
            - '@OswisOrg\OswisCalendarBundle\Repository\ParticipantMailCategoryRepository'
            - '@OswisOrg\OswisCalendarBundle\Repository\ParticipantMailRepository'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\ParticipantMailService:
        alias: oswis_org_oswis_calendar.participant_mail_service
        public: true

    oswis_org_oswis_calendar.participant_category_service:
        class: OswisOrg\OswisCalendarBundle\Service\ParticipantCategoryService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\ParticipantCategoryService:
        alias: oswis_org_oswis_calendar.participant_category_service
        public: true

    oswis_org_oswis_calendar.reg_range_service:
        class: OswisOrg\OswisCalendarBundle\Service\RegRangeService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
            - '@oswis_org_oswis_calendar.flag_range_service'
    OswisOrg\OswisCalendarBundle\Service\RegRangeService:
        alias: oswis_org_oswis_calendar.reg_range_service
        public: true

    ###
    ###  REPOSITORY
    ###

    OswisOrg\OswisCalendarBundle\Repository\EventRepository:
        class: OswisOrg\OswisCalendarBundle\Repository\EventRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'

    OswisOrg\OswisCalendarBundle\Repository\FlagRangeRepository:
        class: OswisOrg\OswisCalendarBundle\Repository\FlagRangeRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'

    OswisOrg\OswisCalendarBundle\Repository\ParticipantRepository:
        class: OswisOrg\OswisCalendarBundle\Repository\ParticipantRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'

    OswisOrg\OswisCalendarBundle\Repository\ParticipantTokenRepository:
        class: OswisOrg\OswisCalendarBundle\Repository\ParticipantTokenRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'

    OswisOrg\OswisCalendarBundle\Repository\ParticipantMailRepository:
        class: OswisOrg\OswisCalendarBundle\Repository\ParticipantMailRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'

    OswisOrg\OswisCalendarBundle\Repository\ParticipantMailCategoryRepository:
        class: OswisOrg\OswisCalendarBundle\Repository\ParticipantMailCategoryRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'

    OswisOrg\OswisCalendarBundle\Repository\ParticipantMailGroupRepository:
        class: OswisOrg\OswisCalendarBundle\Repository\ParticipantMailGroupRepository
        autowire: true
        public: true
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'

    ###
    ### SUBSCRIBERS
    ###

    oswis_org_oswis_calendar.participant_payment_subscriber:
        class: OswisOrg\OswisCalendarBundle\EventSubscriber\ParticipantPaymentSubscriber
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.participant_payment_service'

    oswis_org_oswis_calendar.participant_payments_import_subscriber:
        class: OswisOrg\OswisCalendarBundle\EventSubscriber\ParticipantPaymentsImportSubscriber
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.participant_payments_import_service'

    oswis_org_oswis_calendar.participant_subscriber:
        class: OswisOrg\OswisCalendarBundle\EventSubscriber\ParticipantSubscriber
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.participant_mail_service'
            - '@monolog.logger'

    ## Participant list action (/participant_list_action)
    ## Sends pdf with Participants by e-mail.
    oswis_org_oswis_calendar.participant_list_action_request:
        class: OswisOrg\OswisCalendarBundle\Api\Dto\ParticipantListActionRequest
        autowire: true
        public: true
    OswisOrg\OswisCalendarBundle\Api\Dto\ParticipantListActionRequest:
        alias: oswis_org_oswis_calendar.participant_list_action_request
        public: true
    oswis_org_oswis_calendar.participant_list_action_subscriber:
        class: OswisOrg\OswisCalendarBundle\Api\EventSubscriber\ParticipantListActionSubscriber
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_core.export_service'
            - '@doctrine.orm.entity_manager'
            - '@oswis_org_oswis_calendar.participant_service'
    OswisOrg\OswisCalendarBundle\Api\EventSubscriber\ParticipantListActionSubscriber:
        alias: oswis_org_oswis_calendar.participant_list_action_subscriber
        public: true

    ## Event action (/event_action)
    oswis_org_oswis_calendar.event_action_request:
        class: OswisOrg\OswisCalendarBundle\Api\Dto\EventActionRequest
        autowire: true
        public: true
    OswisOrg\OswisCalendarBundle\Api\Dto\EventActionRequest:
        alias: oswis_org_oswis_calendar.event_action_request
        public: true
    oswis_org_oswis_calendar.event_action_subscriber:
        class: OswisOrg\OswisCalendarBundle\Api\EventSubscriber\EventActionSubscriber
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.participant_service'
    OswisOrg\OswisCalendarBundle\Api\EventSubscriber\EventActionSubscriber:
        alias: oswis_org_oswis_calendar.event_action_subscriber
        public: true


    ###
    ### FORMS
    ###

    oswis_org_oswis_calendar.participant_type:
        class: OswisOrg\OswisCalendarBundle\Form\Participant\ParticipantType
        autowire: true
        public: true
    OswisOrg\OswisCalendarBundle\Form\Participant\ParticipantType:
        alias: oswis_org_oswis_calendar.participant_type
        public: true

    oswis_org_oswis_calendar.participant_flag_group_type:
        class: OswisOrg\OswisCalendarBundle\Form\Participant\ParticipantFlagGroupType
        autowire: true
        public: true
    OswisOrg\OswisCalendarBundle\Form\Participant\ParticipantFlagGroupType:
        alias: oswis_org_oswis_calendar.participant_flag_group_type
        public: true

    ###
    ### OSWIS CALENDAR SETTINGS PROVIDER
    ###
    oswis_org_oswis_calendar.oswis_calendar_settings_provider:
        class: OswisOrg\OswisCalendarBundle\Provider\OswisCalendarSettingsProvider
        autowire: true
        public: true
    OswisOrg\OswisCalendarBundle\Provider\OswisCalendarSettingsProvider:
        alias: oswis_org_oswis_calendar.oswis_calendar_settings_provider
        public: true
