services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Zakjakub\OswisCalendarBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
        public: true

    zakjakub_oswis_calendar.event_participant_payment_subscriber:
        class: Zakjakub\OswisCalendarBundle\EventSubscriber\EventParticipantPaymentSubscriber
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@mailer.mailer'
            - '@monolog.logger'
            - '@zakjakub_oswis_core.oswis_core_settings_provider'

    zakjakub_oswis_calendar.event_participant_subscriber:
        class: Zakjakub\OswisCalendarBundle\EventSubscriber\EventParticipantSubscriber
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@mailer.mailer'
            - '@monolog.logger'
            - '@zakjakub_oswis_core.oswis_core_settings_provider'
            - '@security.user_password_encoder.generic'

    zakjakub_oswis_calendar.event_participant_controller:
        class: Zakjakub\OswisCalendarBundle\Controller\EventParticipantController
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
            - '@security.user_password_encoder.generic'
            - '@zakjakub_oswis_core.oswis_core_settings_provider'
            - '@mailer.mailer'

    zakjakub_oswis_calendar.event_participant_payment_action_request:
        class: Zakjakub\OswisCalendarBundle\Api\Dto\EventParticipantPaymentActionRequest
        autowire: true
        public: true

    zakjakub_oswis_calendar.event_participant_payment_action_subscriber:
        class: Zakjakub\OswisCalendarBundle\Api\EventSubscriber\EventParticipantPaymentActionSubscriber
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@mailer.mailer'
            - '@monolog.logger'
            - '@zakjakub_oswis_core.oswis_core_settings_provider'

