services:

    Zakjakub\OswisCalendarBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
        public: true

    Zakjakub\OswisCalendarBundle\EventSubscriber\:
        resource: '../../EventSubscriber/*'
        tags: [ { name: 'kernel.view'} ]
        # arguments:
        #   ['@security.user_password_encoder.generic', '@doctrine.orm.entity_manager.abstract', '@swiftmailer.mailer.abstract', '@monolog.logger_prototype', '@twig', '@security.token_storage']
        public: true

    Zakjakub\OswisCalendarBundle\EventListener\:
        resource: '../../EventListener/*'
        # arguments:
        #   ['@security.user_password_encoder.generic', '@doctrine.orm.entity_manager.abstract', '@swiftmailer.mailer.abstract', '@monolog.logger_prototype', '@twig', '@security.token_storage']
        public: true




    zakjakub_oswis_calendar.event_participant_controller:
        class: Zakjakub\OswisCalendarBundle\Controller\EventParticipantController
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
            - '@security.user_password_encoder.generic'
            - '@zakjakub_oswis_core.oswis_core_settings_provider'
            - '@mailer.mailer'

    zakjakub_oswis_calendar.event_participant_payment_action_request:
        class: Zakjakub\OswisCalendarBundle\Api\Dto\EventParticipantPaymentActionRequest
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@mailer.mailer'
            - '@monolog.logger'
            - '@zakjakub_oswis_core.oswis_core_settings_provider'

    zakjakub_oswis_calendar.event_participant_payment_action_subscriber:
        class: Zakjakub\OswisCalendarBundle\Api\EventSubscriber\EventParticipantPaymentActionSubscriber
        autowire: true
        public: true

