services:

    Zakjakub\OswisCalendarBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
        public: true

    zakjakub_oswis_calendar.event_participant_controller:
        class: Zakjakub\OswisCalendarBundle\Controller\EventParticipantController
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
            - '@security.user_password_encoder.generic'
            - '@zakjakub_oswis_core.oswis_core_settings_provider'
            - '@mailer.mailer'


    Zakjakub\OswisCalendarBundle\Api\Dto\:
        resource: '../../Api/Dto/*'
        public: true

    Zakjakub\OswisCalendarBundle\Api\EventSubscriber\:
        resource: '../../Api/EventSubscriber/*'
        public: true

