##
## OswisCalendarBundle - Services configuration
## oswis-org/oswis-calendar-bundle/Resources/config/services.yaml
##
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    ##
    ## Controllers wildcard (TODO: To be refactored. Do not use wildcards.)
    ##
    OswisOrg\OswisCalendarBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
        public: true

    ##
    ## EventParticipant payment subscriber (checks etc.)
    ##
    oswis_org_oswis_calendar.event_participant_payment_subscriber:
        class: OswisOrg\OswisCalendarBundle\EventSubscriber\EventParticipantPaymentSubscriber
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.event_participant_payment_service'

    ##
    ## EventParticipant subscriber (checks etc.)
    ##
    oswis_org_oswis_calendar.event_participant_subscriber:
        class: OswisOrg\OswisCalendarBundle\EventSubscriber\EventParticipantSubscriber
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.event_participant_service'
            - '@oswis_org_oswis_calendar.event_service'

    ### Event Service
    oswis_org_oswis_calendar.event_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\EventService:
        alias: oswis_org_oswis_calendar.event_service
        public: true

    ### EventFlag Service
    oswis_org_oswis_calendar.event_flag_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventFlagService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\EventFlagService:
        alias: oswis_org_oswis_calendar.event_flag_service
        public: true

    ### EventType Service
    oswis_org_oswis_calendar.event_type_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventTypeService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\EventTypeService:
        alias: oswis_org_oswis_calendar.event_type_service
        public: true

    ### EventSeries Service
    oswis_org_oswis_calendar.event_series_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventSeriesService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\EventSeriesService:
        alias: oswis_org_oswis_calendar.event_series_service
        public: true

    ### EventParticipantType Service
    oswis_org_oswis_calendar.event_participant_type_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventParticipantTypeService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\EventParticipantTypeService:
        alias: oswis_org_oswis_calendar.event_participant_type_service
        public: true

    ### EventParticipantTypeInEventConnection Service
    oswis_org_oswis_calendar.event_participant_type_in_event_connection_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventParticipantTypeInEventConnectionService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\EventParticipantTypeInEventConnectionService:
        alias: oswis_org_oswis_calendar.event_participant_type_in_event_connection_service
        public: true

    ### EventParticipantPayment Service
    oswis_org_oswis_calendar.event_participant_payment_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventParticipantPaymentService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@mailer.mailer'
            - '@monolog.logger'
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
    OswisOrg\OswisCalendarBundle\Service\EventParticipantPaymentService:
        alias: oswis_org_oswis_calendar.event_participant_payment_service
        public: true

    ### EventParticipant Service
    oswis_org_oswis_calendar.event_participant_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventParticipantService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@mailer.mailer'
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\EventParticipantService:
        alias: oswis_org_oswis_calendar.event_participant_service
        public: true

    ### EventParticipantFlagType Service
    oswis_org_oswis_calendar.event_participant_flag_type_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventParticipantFlagTypeService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\EventParticipantFlagTypeService:
        alias: oswis_org_oswis_calendar.event_participant_flag_type_service
        public: true

    ### EventParticipantFlag Service
    oswis_org_oswis_calendar.event_participant_flag_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventParticipantFlagService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\EventParticipantFlagService:
        alias: oswis_org_oswis_calendar.event_participant_flag_service
        public: true

    ##
    ## EventParticipant controller (What does this?)
    ##
    oswis_org_oswis_calendar.event_participant_controller:
        class: OswisOrg\OswisCalendarBundle\Controller\EventParticipantController
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
            - '@security.user_password_encoder.generic'
            - '@oswis_org_oswis_calendar.event_service'
            - '@oswis_org_oswis_calendar.event_participant_type_service'
            - '@oswis_org_oswis_address_book.address_book_service'
    OswisOrg\OswisCalendarBundle\Controller\EventParticipantController:
        alias: oswis_org_oswis_calendar.event_participant_controller
        public: true

    ##
    ## Event web controller.
    ##
    oswis_org_oswis_calendar.event_controller:
        class: OswisOrg\OswisCalendarBundle\Controller\EventController
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.event_service'
            - '@oswis_org_oswis_calendar.event_participant_type_service'
    OswisOrg\OswisCalendarBundle\Controller\EventController:
        alias: oswis_org_oswis_calendar.event_controller
        public: true

    ##
    ## EventParticipant payment action (/event_participant_payment_action)
    ##
    oswis_org_oswis_calendar.event_participant_payment_action_request:
        class: OswisOrg\OswisCalendarBundle\Api\Dto\EventParticipantPaymentActionRequest
        autowire: true
        public: true
    OswisOrg\OswisCalendarBundle\Api\Dto\EventParticipantPaymentActionRequest:
        alias: oswis_org_oswis_calendar.event_participant_payment_action_request
        public: true
    oswis_org_oswis_calendar.event_participant_payment_action_subscriber:
        class: OswisOrg\OswisCalendarBundle\Api\EventSubscriber\EventParticipantPaymentActionSubscriber
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oswis_org_oswis_calendar.event_participant_payment_service'
    OswisOrg\OswisCalendarBundle\Api\EventSubscriber\EventParticipantPaymentActionSubscriber:
        alias: oswis_org_oswis_calendar.event_participant_payment_action_subscriber
        public: true

    ##
    ## EventParticipant list action (/event_participant_list_action)
    ## Sends pdf with eventParticipants by e-mail.
    ##
    oswis_org_oswis_calendar.event_participant_list_action_request:
        class: OswisOrg\OswisCalendarBundle\Api\Dto\EventParticipantListActionRequest
        autowire: true
        public: true
    OswisOrg\OswisCalendarBundle\Api\Dto\EventParticipantListActionRequest:
        alias: oswis_org_oswis_calendar.event_participant_list_action_request
        public: true
    oswis_org_oswis_calendar.event_participant_list_action_subscriber:
        class: OswisOrg\OswisCalendarBundle\Api\EventSubscriber\EventParticipantListActionSubscriber
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_core.export_service'
            - '@doctrine.orm.entity_manager'
            - '@oswis_org_oswis_calendar.event_participant_service'
    OswisOrg\OswisCalendarBundle\Api\EventSubscriber\EventParticipantListActionSubscriber:
        alias: oswis_org_oswis_calendar.event_participant_list_action_subscriber
        public: true

    ##
    ## Event action (/event_action)
    ##
    oswis_org_oswis_calendar.event_action_request:
        class: OswisOrg\OswisCalendarBundle\Api\Dto\EventActionRequest
        autowire: true
        public: true
    OswisOrg\OswisCalendarBundle\Api\Dto\EventActionRequest:
        alias: oswis_org_oswis_calendar.event_action_request
        public: true
    oswis_org_oswis_calendar.event_action_subscriber:
        class: OswisOrg\OswisCalendarBundle\Api\EventSubscriber\EventActionSubscriber
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.event_participant_service'
    OswisOrg\OswisCalendarBundle\Api\EventSubscriber\EventActionSubscriber:
        alias: oswis_org_oswis_calendar.event_action_subscriber
        public: true

    ### EventParticipantType (form)
    oswis_org_oswis_calendar.event_participant_type:
        class: OswisOrg\OswisCalendarBundle\Form\EventParticipant\EventParticipantType
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.event_service'
            - '@oswis_org_oswis_calendar.event_series_service'
    OswisOrg\OswisCalendarBundle\Form\EventParticipant\EventParticipantType:
        alias: oswis_org_oswis_calendar.event_participant_type
        public: true

    ### OSWIS Calendar Settings Provider
    oswis_org_oswis_calendar.oswis_calendar_settings_provider:
        class: OswisOrg\OswisCalendarBundle\Provider\OswisCalendarSettingsProvider
        autowire: true
        public: true
    OswisOrg\OswisCalendarBundle\Provider\OswisCalendarSettingsProvider:
        alias: oswis_org_oswis_calendar.oswis_calendar_settings_provider
        public: true
