##
## OswisCalendarBundle - Services configuration
## oswis-org/oswis-calendar-bundle/Resources/config/services.yaml
##
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    ###
    ### CONTROLLERS
    ###

    ## Controllers wildcard (TODO: To be refactored. Do not use wildcards.)
    OswisOrg\OswisCalendarBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
        public: true

    ## Event controller.
    oswis_org_oswis_calendar.event_controller:
        class: OswisOrg\OswisCalendarBundle\Controller\EventController
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.event_service'
            - '@oswis_org_oswis_calendar.participant_service'
            - '@oswis_org_oswis_calendar.registrations_range_service'
    OswisOrg\OswisCalendarBundle\Controller\EventController:
        alias: oswis_org_oswis_calendar.event_controller
        public: true

    ## Participant controller
    oswis_org_oswis_calendar.participant_controller:
        class: OswisOrg\OswisCalendarBundle\Controller\ParticipantController
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.participant_service'
    OswisOrg\OswisCalendarBundle\Controller\ParticipantController:
        alias: oswis_org_oswis_calendar.participant_controller
        public: true

    ##
    ## Registration controller
    ##
    oswis_org_oswis_calendar.registration_controller:
        class: OswisOrg\OswisCalendarBundle\Controller\RegistrationController
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
            - '@oswis_org_oswis_calendar.event_service'
            - '@oswis_org_oswis_calendar.registrations_range_service'
            - '@oswis_org_oswis_address_book.address_book_service'
            - '@oswis_org_oswis_calendar.participant_service'
    OswisOrg\OswisCalendarBundle\Controller\RegistrationController:
        alias: oswis_org_oswis_calendar.registration_controller
        public: true



    ###
    ### SERVICES
    ###

    ### EventFlag Service
    oswis_org_oswis_calendar.event_flag_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventFlagService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\EventFlagService:
        alias: oswis_org_oswis_calendar.event_flag_service
        public: true

    ### EventGroup Service
    oswis_org_oswis_calendar.event_series_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventSeriesService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\EventSeriesService:
        alias: oswis_org_oswis_calendar.event_series_service
        public: true

    ### Event Service
    oswis_org_oswis_calendar.event_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
            - '@oswis_org_oswis_calendar.oswis_calendar_settings_provider'
    OswisOrg\OswisCalendarBundle\Service\EventService:
        alias: oswis_org_oswis_calendar.event_service
        public: true

    ### EventType Service
    oswis_org_oswis_calendar.event_category_service:
        class: OswisOrg\OswisCalendarBundle\Service\EventTypeService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\EventTypeService:
        alias: oswis_org_oswis_calendar.event_category_service
        public: true

    ### ParticipantAggregation Service
    oswis_org_oswis_calendar.participant_aggregation_service:
        class: OswisOrg\OswisCalendarBundle\Service\ParticipantAggregationService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oswis_org_oswis_calendar.participant_service'
    OswisOrg\OswisCalendarBundle\Service\ParticipantAggregationService:
        alias: oswis_org_oswis_calendar.participant_aggregation_service
        public: true

    ### RegistrationsFlagRange Service
    oswis_org_oswis_calendar.participant_category_range_service:
        class: OswisOrg\OswisCalendarBundle\Service\ParticipantFlagRangeService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
    OswisOrg\OswisCalendarBundle\Service\ParticipantFlagRangeService:
        alias: oswis_org_oswis_calendar.participant_category_range_service
        public: true

    ### RegistrationFlag Service
    oswis_org_oswis_calendar.participant_category_service:
        class: OswisOrg\OswisCalendarBundle\Service\ParticipantFlagService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\ParticipantFlagService:
        alias: oswis_org_oswis_calendar.participant_category_service
        public: true

    ### ParticipantFlagType Service
    oswis_org_oswis_calendar.participant_category_category_service:
        class: OswisOrg\OswisCalendarBundle\Service\ParticipantFlagTypeService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\ParticipantFlagTypeService:
        alias: oswis_org_oswis_calendar.participant_category_category_service
        public: true

    ### ParticipantPayment Service
    oswis_org_oswis_calendar.participant_payment_service:
        class: OswisOrg\OswisCalendarBundle\Service\ParticipantPaymentService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@mailer.mailer'
            - '@monolog.logger'
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
            - '@oswis_org_oswis_calendar.participant_service'
    OswisOrg\OswisCalendarBundle\Service\ParticipantPaymentService:
        alias: oswis_org_oswis_calendar.participant_payment_service
        public: true

    ### Participant Service
    oswis_org_oswis_calendar.participant_service:
        class: OswisOrg\OswisCalendarBundle\Service\ParticipantService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@mailer.mailer'
            - '@oswis_org_oswis_core.oswis_core_settings_provider'
            - '@monolog.logger'
            - '@oswis_org_oswis_core.app_user_service'
            - '@oswis_org_oswis_core.export_service'
            - '@security.user_password_encoder.generic'
    OswisOrg\OswisCalendarBundle\Service\ParticipantService:
        alias: oswis_org_oswis_calendar.participant_service
        public: true

    ### ParticipantCategory Service
    oswis_org_oswis_calendar.participant_category_service:
        class: OswisOrg\OswisCalendarBundle\Service\ParticipantTypeService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
    OswisOrg\OswisCalendarBundle\Service\ParticipantTypeService:
        alias: oswis_org_oswis_calendar.participant_category_service
        public: true

    ### RegistrationsRange Service
    oswis_org_oswis_calendar.registrations_range_service:
        class: OswisOrg\OswisCalendarBundle\Service\RegistrationsRangeService
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@monolog.logger'
            - '@oswis_org_oswis_calendar.participant_category_range_service'
    OswisOrg\OswisCalendarBundle\Service\RegistrationsRangeService:
        alias: oswis_org_oswis_calendar.registrations_range_service
        public: true



    ###
    ### SUBSCRIBERS
    ###

    ## Participant payment subscriber (checks etc.)
    oswis_org_oswis_calendar.participant_payment_subscriber:
        class: OswisOrg\OswisCalendarBundle\EventSubscriber\ParticipantPaymentSubscriber
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.participant_payment_service'

    ## Participant subscriber (checks etc.)
    oswis_org_oswis_calendar.participant_subscriber:
        class: OswisOrg\OswisCalendarBundle\EventSubscriber\ParticipantSubscriber
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.participant_service'

    ## Participant payment action (/participant_payment_action)
    oswis_org_oswis_calendar.participant_payment_action_request:
        class: OswisOrg\OswisCalendarBundle\Api\Dto\ParticipantPaymentActionRequest
        autowire: true
        public: true
    OswisOrg\OswisCalendarBundle\Api\Dto\ParticipantPaymentActionRequest:
        alias: oswis_org_oswis_calendar.participant_payment_action_request
        public: true
    oswis_org_oswis_calendar.participant_payment_action_subscriber:
        class: OswisOrg\OswisCalendarBundle\Api\EventSubscriber\ParticipantPaymentActionSubscriber
        autowire: true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oswis_org_oswis_calendar.participant_payment_service'
    OswisOrg\OswisCalendarBundle\Api\EventSubscriber\ParticipantPaymentActionSubscriber:
        alias: oswis_org_oswis_calendar.participant_payment_action_subscriber
        public: true

    ## Participant list action (/participant_list_action)
    ## Sends pdf with Participants by e-mail.
    oswis_org_oswis_calendar.participant_list_action_request:
        class: OswisOrg\OswisCalendarBundle\Api\Dto\ParticipantListActionRequest
        autowire: true
        public: true
    OswisOrg\OswisCalendarBundle\Api\Dto\ParticipantListActionRequest:
        alias: oswis_org_oswis_calendar.participant_list_action_request
        public: true
    oswis_org_oswis_calendar.participant_list_action_subscriber:
        class: OswisOrg\OswisCalendarBundle\Api\EventSubscriber\ParticipantListActionSubscriber
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_core.export_service'
            - '@doctrine.orm.entity_manager'
            - '@oswis_org_oswis_calendar.participant_service'
    OswisOrg\OswisCalendarBundle\Api\EventSubscriber\ParticipantListActionSubscriber:
        alias: oswis_org_oswis_calendar.participant_list_action_subscriber
        public: true

    ## Event action (/event_action)
    oswis_org_oswis_calendar.event_action_request:
        class: OswisOrg\OswisCalendarBundle\Api\Dto\EventActionRequest
        autowire: true
        public: true
    OswisOrg\OswisCalendarBundle\Api\Dto\EventActionRequest:
        alias: oswis_org_oswis_calendar.event_action_request
        public: true
    oswis_org_oswis_calendar.event_action_subscriber:
        class: OswisOrg\OswisCalendarBundle\Api\EventSubscriber\EventActionSubscriber
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.participant_service'
    OswisOrg\OswisCalendarBundle\Api\EventSubscriber\EventActionSubscriber:
        alias: oswis_org_oswis_calendar.event_action_subscriber
        public: true


    ###
    ### FORMS
    ###

    ### ParticipantCategory (form)
    oswis_org_oswis_calendar.registration_form_type:
        class: OswisOrg\OswisCalendarBundle\Form\Participant\RegistrationFormType
        autowire: true
        public: true
        arguments:
            - '@oswis_org_oswis_calendar.event_service'
            - '@oswis_org_oswis_calendar.event_series_service'
    OswisOrg\OswisCalendarBundle\Form\Participant\RegistrationFormType:
        alias: oswis_org_oswis_calendar.registration_form_type
        public: true


    ###
    ### OSWIS CALENDAR SETTINGS PROVIDER
    ###
    oswis_org_oswis_calendar.oswis_calendar_settings_provider:
        class: OswisOrg\OswisCalendarBundle\Provider\OswisCalendarSettingsProvider
        autowire: true
        public: true
    OswisOrg\OswisCalendarBundle\Provider\OswisCalendarSettingsProvider:
        alias: oswis_org_oswis_calendar.oswis_calendar_settings_provider
        public: true
