OswisOrg\OswisCalendarBundle\Entity\Participant\Participant:
    attributes:
        participantCategory:
            groups: [ 'calendar_participants_get', 'calendar_participant_get' ]
        notes:
            groups: [ 'calendar_participants_get', 'calendar_participants_post', 'calendar_participant_get', 'calendar_participant_put' ]
        regRange:
            groups: [ 'calendar_participants_get', 'calendar_participants_post', 'calendar_participant_get', 'calendar_participant_put' ]
        contact:
            groups: [ 'calendar_participants_get', 'calendar_participant_get' ]
        event:
            groups: [ 'calendar_participants_get', 'calendar_participant_get' ]
        flagGroups:
            groups: [ 'calendar_participants_get', 'calendar_participants_post', 'calendar_participant_get', 'calendar_participant_put' ]
        priceRest:
            groups: [ 'calendar_participants_get', 'calendar_participant_get' ]
        priceDeposit:
            groups: [ 'calendar_participants_get', 'calendar_participant_get' ]
        price:
            groups: [ 'calendar_participants_get', 'calendar_participant_get' ]
        remainingPrice:
            groups: [ 'calendar_participants_get', 'calendar_participant_get' ]
        paidPrice:
            groups: [ 'calendar_participants_get', 'calendar_participant_get' ]
        activatedContactUser:
            groups: [ 'calendar_participants_get', 'calendar_participant_get' ]
        variableSymbol:
            groups: [ 'calendar_participants_get', 'calendar_participant_get' ]

OswisOrg\OswisCalendarBundle\Entity\Participant\ParticipantFlagGroup:
    attributes:
        id:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participants_post'
                - 'calendar_participant_get'
                - 'calendar_participant_put'
        participantFlags:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participants_post'
                - 'calendar_participant_get'
                - 'calendar_participant_put'
        name:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        active:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'

OswisOrg\OswisCalendarBundle\Entity\Registration\ParticipantFlagOffer:
    attributes:
        id:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participants_post'
                - 'calendar_participant_get'
                - 'calendar_participant_put'

OswisOrg\OswisCalendarBundle\Entity\Registration\ParticipantOffer:
    attributes:
        id:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participants_post'
                - 'calendar_participant_get'
                - 'calendar_participant_put'

OswisOrg\OswisCalendarBundle\Entity\Participant\FlagOfParticipant:
    attributes:
        id:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participants_post'
                - 'calendar_participant_get'
                - 'calendar_participant_put'
        name:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        extendedName:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        shortName:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        description:
            groups:
                - 'calendar_participant_get'
        note:
            groups:
                - 'calendar_participant_get'
        internalNote:
            groups:
                - 'calendar_participant_get'
        slug:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        valueAllowed:
            groups:
                - 'calendar_participant_get'
        valueLabel:
            groups:
                - 'calendar_participant_get'
        valueRegex:
            groups:
                - 'calendar_participant_get'
        color:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        price:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        active:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        flagRange:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participants_post'
                - 'calendar_participant_get'
                - 'calendar_participant_put'

OswisOrg\OswisCalendarBundle\Entity\Participant\ParticipantPayment:
    attributes:
        numericValue:
            groups:
                - 'calendar_participant_get'
        note:
            groups:
                - 'calendar_participant_get'
        internalNote:
            groups:
                - 'calendar_participant_get'
        eMailConfirmationDateTime:
            groups:
                - 'calendar_participant_get'
        eMailConfirmationCount:
            groups:
                - 'calendar_participant_get'
        eMailConfirmationSource:
            groups:
                - 'calendar_participant_get'

OswisOrg\OswisCalendarBundle\Entity\Participant\ParticipantNote:
    attributes:
        publicNote:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        deleted:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'

OswisOrg\OswisAddressBookBundle\Entity\AbstractClass\AbstractContact:
    attributes:
        name:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        contactName:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        details:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        sortableName:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        phone:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        url:
            groups:
                - 'calendar_participant_get'
        email:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        gender:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'


OswisOrg\OswisCalendarBundle\Entity\Event\Event:
    attributes:
        id:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        name:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        superEvent:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'



OswisOrg\OswisAddressBookBundle\Entity\ContactDetail:
    attributes:
        id:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        detailCategory:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        name:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        shortName:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        description:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        priority:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        content:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        formatted:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        schemaString:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        categoryString:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        categoryName:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        showInPreview:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'

OswisOrg\OswisAddressBookBundle\Entity\ContactDetailCategory:
    attributes:
        id:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        name:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        shortName:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        type:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        priority:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        content:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        formatted:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        schemaString:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'
        typeString:
            groups:
                - 'calendar_participants_get'
                - 'calendar_participant_get'


