OswisOrg\OswisCalendarBundle\Entity\Participant\ParticipantNote:
    attributes:
        textValue:
            groups: [ 'calendar_participant_notes_get', 'calendar_participant_notes_post', 'calendar_participant_note_get', 'calendar_participant_note_put' ]
        publicNote:
            groups: [ 'calendar_participant_notes_get', 'calendar_participant_notes_post', 'calendar_participant_note_get', 'calendar_participant_note_put' ]
        deleted:
            groups: [ 'calendar_participant_notes_get', 'calendar_participant_notes_post', 'calendar_participant_note_get', 'calendar_participant_note_put' ]

OswisOrg\OswisCalendarBundle\Entity\Participant\Participant:
    attributes:
        id:
            groups: [ 'calendar_participant_notes_get', 'calendar_participant_notes_post', 'calendar_participant_note_get', 'calendar_participant_note_put' ]

