OswisOrg\OswisCalendarBundle\Entity\Participant\ParticipantFlagGroup:
    attributes:
        flagGroupOffer:
            groups:
                - 'calendar_participant_flag_group_get'
                - 'calendar_participant_flag_groups_get'
        min:
            groups:
                - 'calendar_participant_flag_group_get'
                - 'calendar_participant_flag_groups_get'
        max:
            groups:
                - 'calendar_participant_flag_group_get'
                - 'calendar_participant_flag_groups_get'
        availableFlagOffers:
            groups:
                - 'calendar_participant_flag_group_get'
                - 'calendar_participant_flag_groups_get'
        participantFlags:
            groups:
                - 'calendar_participant_flag_group_get'
                - 'calendar_participant_flag_groups_get'
                - 'calendar_participant_flag_groups_put'



