<?php

declare(strict_types=1);

namespace OswisOrg\OswisCalendarBundle\Exception;

use Exception;

/**
 * Thrown by YearCloneService when the target year slug (or any slug that
 * would be generated by smart substitution) already exists in the
 * persistence layer. Guards the precondition that two events cannot
 * share a slug.
 *
 * Spec: docs/superpowers/specs/2026-05-21-S5-year-clone-wizard-design.md
 */
final class DuplicateSlugException extends Exception
{
    public function __construct(string $slug)
    {
        parent::__construct(sprintf('Event with slug "%s" already exists.', $slug));
    }
}
